# Etapa 1: Construcción
FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build

# Etapa 2: Servir el frontend estático con Nginx
FROM nginx:1.25-alpine

# Copiamos la build al directorio por defecto de Nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# Exponer el puerto donde escucha Nginx
EXPOSE 5173

# Reemplazar configuración de NGINX para servir front SPA correctamente
COPY nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
